"""fitness domain rewrite: drop keepsakes, add programs/exercises/workouts/achievements

Revision ID: 561d62621de3
Revises: e5654ef0a8e7
Create Date: 2026-08-27 14:45:54.889832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.seed_data import ACHIEVEMENTS, EXERCISES

# revision identifiers, used by Alembic.
revision: str = '561d62621de3'
down_revision: Union[str, None] = 'e5654ef0a8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_key'), 'achievements', ['key'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_muscles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secondary_muscles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('execution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pro_cues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supports_camera', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('camera_view', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_table('body_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_metrics_user_id'), 'body_metrics', ['user_id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('split_type', sa.String(length=32), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_owner_id'), 'programs', ['owner_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('progress_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('program_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('muscle_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_rest', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_days_program_id'), 'program_days', ['program_id'], unique=False)
    op.create_table('program_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_day_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('rep_range_low', sa.Integer(), nullable=False),
    sa.Column('rep_range_high', sa.Integer(), nullable=False),
    sa.Column('load_type', sa.String(length=16), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('tempo', sa.String(length=16), nullable=True),
    sa.Column('superset_group', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('coach_with_camera', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_exercises_program_day_id'), 'program_exercises', ['program_day_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('program_day_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_form_score', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=16), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('form_score', sa.Integer(), nullable=True),
    sa.Column('depth_pct', sa.Float(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_session_id'), 'workout_sets', ['session_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('est_1rm_kg', sa.Float(), nullable=False),
    sa.Column('workout_set_id', sa.UUID(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_set_id'], ['workout_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    op.drop_table('keepsakes')
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('goal', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('days_per_week', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('session_minutes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('split_preference', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('gym_location', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('injuries', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('units', sa.String(length=16), server_default='metric', nullable=False))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('voice_coach', postgresql.JSONB(astext_type=sa.Text()), server_default='{"enabled": true, "verbosity": "standard", "voice": "alex_en_gb", "count_reps": false, "encouragement": true, "volume": 0.7, "duck_music": true}', nullable=False))
    op.add_column('users', sa.Column('rest_timer_default_s', sa.Integer(), server_default='90', nullable=False))
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=16), server_default='free', nullable=False))
    # ### end Alembic commands ###

    exercises_table = sa.table(
        'exercises',
        sa.column('id', sa.UUID()),
        sa.column('slug', sa.String()),
        sa.column('name', sa.String()),
        sa.column('primary_muscles', postgresql.JSONB()),
        sa.column('secondary_muscles', postgresql.JSONB()),
        sa.column('equipment', postgresql.JSONB()),
        sa.column('difficulty', sa.String()),
        sa.column('execution_steps', postgresql.JSONB()),
        sa.column('pro_cues', postgresql.JSONB()),
        sa.column('mistakes', postgresql.JSONB()),
        sa.column('supports_camera', sa.Boolean()),
        sa.column('camera_view', sa.String()),
    )
    op.bulk_insert(exercises_table, EXERCISES)

    achievements_table = sa.table(
        'achievements',
        sa.column('id', sa.UUID()),
        sa.column('key', sa.String()),
        sa.column('category', sa.String()),
        sa.column('title', sa.String()),
        sa.column('description', sa.String()),
        sa.column('icon', sa.String()),
        sa.column('criteria', postgresql.JSONB()),
        sa.column('is_secret', sa.Boolean()),
    )
    op.bulk_insert(achievements_table, ACHIEVEMENTS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'xp')
    op.drop_column('users', 'rest_timer_default_s')
    op.drop_column('users', 'voice_coach')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'units')
    op.drop_column('users', 'injuries')
    op.drop_column('users', 'equipment')
    op.drop_column('users', 'gym_location')
    op.drop_column('users', 'split_preference')
    op.drop_column('users', 'session_minutes')
    op.drop_column('users', 'days_per_week')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'goal')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'avatar_url')
    op.create_table('keepsakes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('memory_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='keepsakes_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='keepsakes_pkey')
    )
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_workout_sets_session_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_program_exercises_program_day_id'), table_name='program_exercises')
    op.drop_table('program_exercises')
    op.drop_index(op.f('ix_program_days_program_id'), table_name='program_days')
    op.drop_table('program_days')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_programs_owner_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_body_metrics_user_id'), table_name='body_metrics')
    op.drop_table('body_metrics')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_achievements_key'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
