"""add keepsake fields, users/uploads

Revision ID: e5654ef0a8e7
Revises: c2a32e92d88f
Create Date: 2026-08-27 13:00:19.749173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5654ef0a8e7'
down_revision: Union[str, None] = 'c2a32e92d88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keepsakes', sa.Column('memory_date', sa.Date(), nullable=True))
    op.add_column('keepsakes', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keepsakes', 'is_favorite')
    op.drop_column('keepsakes', 'memory_date')
    # ### end Alembic commands ###
